name: build 11ty site

on:
  push:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
      - name: npm ci & build
      - run: npm ci
      - run: npm npx @11ty/eleventy
      
      - name: deploy
      uses: actions/deploy-pages@v3
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}